services:
  - type: web
    name: group-project-manager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 wsgi:app"
    plan: free
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        sync: false
